theme = "modern"
icons = "awesome5"

[[block]]
block = "custom"
command = ''' bash -c 'curl "https://api.kexp.org/v2/plays/?format=json&limit=1&ordering=-airdate&airdate_before=$(date -u +%FT%T.000Z)"' | jq -r '.results[0] | "KEXP: \(.artist) - \(.song)"' '''

[[block]]
block = "pacman"
format = "{pacman}/{aur}"
critical_updates_regex = "zfs"
warning_updates_regex = "(linux|systemd|dbus)"
aur_command = "yay -Qua"

[[block]]
block = "time"
interval = 60
format = "%R %Z"
timezone = "UTC"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m} {5m}"
info = 2.0
warning = 4.0
critical = 6.0

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "networkmanager"
primary_only = true

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "bluetooth"
mac = "B8:27:EB:91:72:07"

[[block]]
block = "music"
marquee = false
smart_trim = true

[[block]]
block = "battery"
format = "{percentage}% {time}"
allow_missing = true
hide_missing = true

[[block]]
block = "time"
interval = 5
format = "%a %Y-%m-%d %R"

[[block]]
block = "custom"
command = ''' hostname '''

